spring.application.name=dispersion-spring-boot-example
server.port=8080
spring.threads.virtual.enabled=true
dispersion.control-plane.base-path=/api/v1
spring.jersey.application-path=/
spring.jersey.type=filter
